### PR TITLE
change rpi-manual ref link

### PR DESCRIPTION
**Pull request by anikaluo**

### CODE REVIEW

**Comment by anikaluo** [comment]
The only thing I changed is the ref link for `rpi-manual`. Should I have made another branch for this?

**Comment by kescobo** [comment]
Typically, you would checkout the main branch, do a pull from there, then start a new branch, yes.

When I merge PRs, I typically do a squash merge, which means the PR commits are all combined into a single commit, which means this is now a different history.

Easiest fix is to do something like:

**Comment by anikaluo** [comment]
Okay, that theoretically makes sense? Is that was I should do for this then?

**Comment by kescobo** [comment]
Yes please

**Comment by anikaluo** [comment]
Wait actually. I'm kind of confused on the steps. Am I executing these commands all in the main branch? That does not seem right. But I'm also not sure when I should be making a new branch?

**Comment by kescobo** [comment]
No, from your current branch. You could also checkout main and just start a whole new branch, closing this PR and opening a new one

**Comment by anikaluo** [comment]
I think I did it? And yes that makes much more sense now.

**Review by kescobo — APPROVED** [review]

**Comment by kescobo** [comment]
Yes! Good work

**Comment by kescobo** [comment]
Now `git checkout main` and `git pull`

**Pull request merged**
